// Shared server-side helpers for talking to mcp-agent-mail and GitHub.
//
// Loaders/actions call these directly via `context.cloudflare.env` instead of
// self-fetching this Worker's own /api/* routes — a same-worker subrequest to
// your own workers.dev URL does not loop back through Hono's router the way
// you'd expect and 404s. workers/app.ts's /api/* routes call these same
// helpers, kept as a thin external-facing surface for other consumers.

// `Env` here is the ambient global type generated by `wrangler types` (vars)
// plus the secret fields merged in via app/env.d.ts.

export type UnifiedMessage = {
	id: number;
	subject: string;
	excerpt: string;
	importance: string;
	sender: string;
	recipients: string;
	project_slug: string;
	project_name: string;
	created_relative: string;
	read: boolean;
};

export type MailAgent = {
	name: string;
	program: string;
	model: string;
	task_description: string;
};

export type SearchResult = {
	id: number;
	subject: string;
	importance: string;
	created_ts: string;
	from: string;
};

export type Task = {
	repo: string;
	number: number;
	title: string;
	url: string;
	state: string;
	labels: string[];
	created_at: string;
	updated_at: string;
};

function agentMailHeaders(env: Env, extra?: Record<string, string>) {
	return {
		"CF-Access-Client-Id": env.CF_ACCESS_CLIENT_ID,
		"CF-Access-Client-Secret": env.CF_ACCESS_CLIENT_SECRET,
		Authorization: `Bearer ${env.AGENT_MAIL_TOKEN}`,
		...extra,
	};
}

// mcp-agent-mail's REST surface only covers 3 read endpoints (unified-inbox,
// projects/{project}/agents, sibling-suggestion). Search and send only exist
// via its MCP JSON-RPC interface at /mcp/.
export async function callAgentMailTool(env: Env, name: string, args: Record<string, unknown>) {
	const res = await fetch(`${env.AGENT_MAIL_URL}/mcp/`, {
		method: "POST",
		headers: agentMailHeaders(env, { "content-type": "application/json" }),
		body: JSON.stringify({
			jsonrpc: "2.0",
			id: crypto.randomUUID(),
			method: "tools/call",
			params: { name, arguments: args },
		}),
	});

	if (!res.ok) {
		throw new Error(`mcp-agent-mail ${name} call failed: ${res.status}`);
	}

	const payload = (await res.json()) as {
		error?: { message: string };
		result?: { content?: Array<{ type: string; text?: string }> };
	};

	if (payload.error) {
		throw new Error(payload.error.message);
	}

	const text = payload.result?.content?.[0]?.text;
	if (!text) return payload.result ?? null;
	try {
		return JSON.parse(text);
	} catch {
		return text;
	}
}

export async function fetchInbox(env: Env): Promise<{ messages: UnifiedMessage[]; error: string | null }> {
	const res = await fetch(`${env.AGENT_MAIL_URL}/mail/api/unified-inbox`, {
		headers: agentMailHeaders(env),
	});
	if (!res.ok) return { messages: [], error: `inbox fetch failed: ${res.status}` };
	const data = (await res.json()) as { messages?: UnifiedMessage[] };
	return { messages: data.messages ?? [], error: null };
}

export async function fetchProjectAgents(
	env: Env,
	project: string,
): Promise<{ agents: MailAgent[]; error: string | null }> {
	const res = await fetch(`${env.AGENT_MAIL_URL}/mail/api/projects/${project}/agents`, {
		headers: agentMailHeaders(env),
	});
	if (!res.ok) return { agents: [], error: `fetch failed: ${res.status}` };
	const data = (await res.json()) as { agents?: MailAgent[] };
	return { agents: data.agents ?? [], error: null };
}

export function listMailProjects(env: Env): string[] {
	return env.AGENT_MAIL_PROJECTS.split(",")
		.map((p) => p.trim())
		.filter(Boolean);
}

export async function searchMessages(
	env: Env,
	project: string,
	query: string,
): Promise<{ result: SearchResult[]; error: string | null }> {
	try {
		const data = (await callAgentMailTool(env, "search_messages", {
			project_key: project,
			query,
			limit: 20,
			ranking: "recency",
		})) as { result?: SearchResult[] };
		return { result: data?.result ?? [], error: null };
	} catch (err) {
		return { result: [], error: (err as Error).message };
	}
}

export async function sendMessage(
	env: Env,
	args: { project: string; sender: string; to: string[]; subject: string; body_md: string },
): Promise<{ ok: boolean; error: string | null }> {
	try {
		await callAgentMailTool(env, "send_message", {
			project_key: args.project,
			sender_name: args.sender,
			to: args.to,
			subject: args.subject,
			body_md: args.body_md,
		});
		return { ok: true, error: null };
	} catch (err) {
		return { ok: false, error: (err as Error).message };
	}
}

export async function fetchGithubTasks(env: Env): Promise<Task[]> {
	const repos = env.GITHUB_REPOS.split(",")
		.map((r) => r.trim())
		.filter(Boolean);

	const results = await Promise.all(
		repos.map(async (repo) => {
			const res = await fetch(`https://api.github.com/repos/${repo}/issues?state=open&per_page=50`, {
				headers: {
					Authorization: `Bearer ${env.GITHUB_TOKEN}`,
					"User-Agent": "agent-mail-inbox-app",
					Accept: "application/vnd.github+json",
				},
			});
			if (!res.ok) return [];
			const issues = (await res.json()) as any[];
			return issues
				.filter((i) => !i.pull_request)
				.map((i) => ({
					repo,
					number: i.number,
					title: i.title,
					url: i.html_url,
					state: i.state,
					labels: (i.labels || []).map((l: any) => (typeof l === "string" ? l : l.name)),
					created_at: i.created_at,
					updated_at: i.updated_at,
				}));
		}),
	);

	return results.flat();
}
